version: '3.8'

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
  rabbitmq:
    image: ${RABBITMQ_IMAGE}
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_HTTP_PORT}:15672"
    volumes:
      - ${RABBITMQ_VOLUME_PATH_DATA}:/var/lib/rabbitmq
      - ${RABBITMQ_VOLUME_PATH_LOG}:/var/log/rabbitmq